{
 "title": "Water Quality Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": " Water Temprature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "temperature", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ambient Temprature ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } }
  },
  {
   "title": "Turbidity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "NTU" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "turbidity", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "pH Value",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ph", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Water Conductivity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": " µmhos" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } }
  }
 ]
}